services:
  postgres:
    image: postgres:15
    container_name: olist_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  superset:
    image: apache/superset:3.0.0
    container_name: olist_superset
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SUPERSET_USER: ${SUPERSET_USER}
      SUPERSET_FIRSTNAME: ${SUPERSET_FIRSTNAME}
      SUPERSET_LASTNAME: ${SUPERSET_LASTNAME}
      SUPERSET_EMAIL: ${SUPERSET_EMAIL}
      SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
      - ./superset/docker-init.sh:/app/docker-init.sh
      - ./sql:/sql
      - ./superset_home:/app/superset_home
    entrypoint: ["/app/docker-init.sh"]

volumes:
  pgdata:
  superset_home: