version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: olist_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: olist_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  superset:
    image: apache/superset:3.0.0
    container_name: olist_superset
    restart: always
    environment:
      SUPERSET_USER: admin
      SUPERSET_PASSWORD: admin
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
      - ./superset/docker-init.sh:/app/docker-init.sh
    entrypoint: ["/app/docker-init.sh"]

volumes:
  pgdata:
